//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BullsNCows
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int Id { get; set; }
        public int Player_ID { get; set; }
        public double Score { get; set; }
        public System.DateTime Date { get; set; }
        public int JournalId { get; set; }
        public int PlayerId { get; set; }
    
        public virtual Player Player { get; set; }
    }
}
